### ISSUE TITLE
Gece Gorus Modu "Ben, Mesaj, Olay" Butonu

### ISSUE THREAD

**Issue by FatihErdem** [serdarcevher/eksinormallestirici#22]
Merhabalar.

Gece gorus modunda bu butonlarin yanindaki iconlar duruyor. Kaldirmaya calistim ama CSS bilgim cok olmadigi icin yapamadim. Goruntu su sekilde. 

![capture](https://cloud.githubusercontent.com/assets/1693329/13425109/67a225de-dfad-11e5-8399-0f670d0ba035.JPG)

Normal moddaki gibi iconlar kaldirilabilirse sevinirim.

**Comment by serdarcevher** [comment]
Merhaba, 0.97 sürümüyle bu sorun düzeliyor, birazdan yayında olur. Bildirim için teşekkürler. :)

**Comment by FatihErdem** [comment]
Cok tesekkurler.
