### ISSUE TITLE
Sayfanin en sonundaki entry'nin altindaki cizgi

### ISSUE THREAD

**Issue by FatihErdem** [serdarcevher/eksinormallestirici#25]
Sayfada tek entry de olsa sayfanin sonundak' entry de olsa altinda cizgi oluyor. Ornek asagida.

![screenshot from 2016-03-01 23-10-53](https://cloud.githubusercontent.com/assets/1693329/13442064/18cd6616-e003-11e5-9bbb-d35dab753105.png)
![screenshot from 2016-03-01 23-12-12](https://cloud.githubusercontent.com/assets/1693329/13442065/18d3e3ec-e003-11e5-8b99-5a2f93c612fc.png)

Bu arada tek tek aciyorum basliklari farkli konular diye. Umarim flood olarak degerlendirmezsiniz. :)

**Comment by serdarcevher** [comment]
Yok yok ne flood'u, teşekkür ederiz raporlar için. :) Ben sadece Pazar günü de dinlenmek yerine bununla uğraştığım için şimdi haftanın 2. gününün sonunda artık pert vaziyetteyim, haftanın kalanında pull request'lere pek bakamayabilirim ama illaki bunlar zamanı gelince düzeltilir.
