### ISSUE TITLE
Entry Arasi Bosluk

### ISSUE THREAD

**Issue by FatihErdem** [serdarcevher/eksinormallestirici#26]
Entry aralarindaki bosluk bir tik daha azaltilirsa daha guzel olabilir. Entry numarasinin boyutu kadar azaltilabilir misal. Teknik olarak oran veremedigim icin boyle demek zorunda kaldim.

**Comment by kerembeyazit** [comment]
Şu an 50 piksel. 20 piksel ideal gibi.

http://postimg.org/image/k2ukinhul/

**Comment by FatihErdem** [comment]
Evet guzel olmus o kadar bosluk. Bunun commitini yapabilir misin acaba?

**Comment by kerembeyazit** [comment]
Teşekkürler Fatih. Maalesef hiç GitHub deneyimim olmadı. Hesabı açmıştım ama hiç kullanmadım, sadece projelerin issue kısımlarında aktif oldum. O yüzden commit yapmayı bilmiyorum.

**Comment by FatihErdem** [comment]
Hocam css degisikligini buraya yazarsan ben commitlerim.

**Comment by kerembeyazit** [comment]
```
#entry-list > li {
    padding: 4px 0px 10px !important;
}
```

**Comment by FatihErdem** [comment]
Tamamdir tesekkurler. Bugun commitlemis olurum.

**Comment by kerembeyazit** [comment]
Kolay gelsin... Commit olayına bakacağım gece bende. Öğrenmek lazım.

**Comment by FatihErdem** [comment]
Olmadi nedense. Aralik degismedi. Atladigim bir sey mi var acaba?

**Comment by kerembeyazit** [comment]
Çakışıyor olabilir belki...

**Comment by FatihErdem** [comment]
Aynen cakisma varmis. Gozumden kacmis. Duzelttim simdi. Tesekkurler.
