### ISSUE TITLE
sub-etha dugmesi birden fazla yere ekleniyor

### ISSUE THREAD

**Issue by kyzn** [serdarcevher/eksinormallestirici#30]
Sub etha dugmesi sadece olay dugmesinin sagindaki menuye degil, ayni zamanda 
- entrylerde yazarin isminin sagindaki dugmeye,
- kanallarin siralandigi barin sonundaki dugmeye,
- sabaha birak seceneginin oldugu dugmeye de ekleniyor

script.js dosyasindaki `$(".dropdown-menu").prepend("...` satiri 5 tane `dropdown-menu` buluyor, bize sadece ilk ikisi gerekiyor. bu satiri `$(".dropdown-menu")[0].prepend("...` seklinde guncellemeyi denedim ancak tam olarak calistiramadim. (0 ve 1 indexleri sag ustte sub-etha dugmesinin gorunmesini istedigimiz menu, 0 webde gosteriliyor 1 mobilde, isterseniz chrome'da `$(".dropdown-menu")` komutuyla inceleyebilirsiniz.

sunu da denedim ama tam olarak calismadi (bu zaten sona ekliyor, basa eklemek icin insertBefore komutunu kullanmak gerekiyordu ama onu da tam ayarlayamadim):

``` js
subethaNode = document.createElement("li");
subethaNode.innerHTML = "<a href='/sub-etha' target='_blank'>sub-etha</a>";
document.getElementsByClassName("dropdown-menu")[0].appendChild(subethaNode)
document.getElementsByClassName("dropdown-menu")[1].appendChild(subethaNode)
```

**Comment by yali4** [comment]
`$(".dropdown-menu")[0]` dediğiniz zaman aldığınız birinci element jQuery wrapper'ının dışına çıktığı için jQuery methodlarını kullanamıyorsunuz. `$(".dropdown-menu").eq(0)` derseniz birinci element jQuery wrapper'ı ile birlikte gelir.

**Comment by kyzn** [comment]
Tesekkurler! Ben de ogrenmis oldum bahaneyle.
