### ISSUE TITLE
Sağ üst dropdown menü hakkında

### ISSUE THREAD

**Issue by kerembeyazit** [serdarcevher/eksinormallestirici#35]
Merhaba. Sadece bende mi öyle bilmiyorum ama menü elemanları sola dayalı gözüküyor;
http://postimg.org/image/mt3wfuejh/

Aşağıdaki kod bu sorunu çözüyor;

```
.dropdown .dropdown-menu li {
    padding-left: 11px;
}
```

**Comment by serdarcevher** [comment]
Bu düzeltmenizi arkadaşlardan biri eklemiş, 0.98 sürümüyle birlikte bu sorun hallolmuş olacak, rapor için teşekkürler!

**Comment by kerembeyazit** [comment]
Teşekkürler.
