### ISSUE TITLE
Firefox eklentisi yüklenmiyor

### ISSUE THREAD

**Issue by ahmedtds** [serdarcevher/eksinormallestirici#37]
Firefox eklenti sayfasında "Not available for Firefox 44.0" yazıyor ve yükleme tuşu aktif değil. Kaç gündür bunun düzeltilmesini bekliyorum yüklemek için. Umarım Firefox 44 için de uyumlu hale getirirsiniz. Şimdiden teşekkürler.

**Comment by thedewil** [comment]
https://github.com/sahtepetrucci/eksinormallestirici/blob/master/firefox/manifest.json dosyasında;

```
"strict_min_version": "44.0"
```

şeklinde düzenleme yapılmanın sorunu çözeceğini düşünüyorum.

**Comment by FatihErdem** [comment]
Eklentinin 45 surumunden itibaren olmasinin sanirim browser tarafinda bir zorlamasi diye hatirliyorum. #10'da belirtiliyor bu.

> Eklenti WebExtensions kullandığı için Firefox 45 ve üstünde çalışıyor. Önümüzdeki hafta stable release olacak bu sürüm.

**Comment by dcelasun** [comment]
Merhaba, evet o yorumu ben yazdım. Bugün/yarın 45 sürümü çıkacak, siz de kurabileceksiniz. Beklemek istemeyenler Firefox beta channel kullanarak hemen geçebilirler.

Bu arada Firefox sürümü ile ilgili sorunlar için beni @ ile mention ederseniz daha hızlı bakabilirim.

**Comment by dcelasun** [comment]
Firefox 45 çıktı ve eklenti 1.0 sürümüyle yayında.
