### ISSUE TITLE
Gece modu uc nokta svg renk sorunu

### ISSUE THREAD

**Issue by FatihErdem** [serdarcevher/eksinormallestirici#44]
Gece modundaki asagidaki uc noktanin rengini degistirdim.

![capture](https://cloud.githubusercontent.com/assets/1693329/13498386/6396c66e-e162-11e5-901e-9a0878ed2be5.JPG)

CSS kodu da su sekilde:

`.dark-theme #top-navigation #options-dropdown .dropdown-toggle.toggles svg{
  fill: #d89630!important;
}`

Ama sayfa yenilendigi zaman once eski haline donup sonradan turuncu oluyor. Bunun sebebi ne olabilir acaba? Anlayamadim.

**Comment by ouzman** [comment]
eklenti geç devreye giriyor olamaz değil mi?

**Comment by FatihErdem** [comment]
Sanirim o kisim sonradan ekleniyor sayfa acildiktan sonra.

**Comment by kerembeyazit** [comment]
`$(window).load(function()` fonksiyonu ile atınabilir o CSS değeri.

**Comment by FatihErdem** [comment]
Sonradan ekleniyor da neden ilk bir saniye default rengi aliyor da sonradan turuncuya donuyor o kismi anlayamadim. Normalde gec acilsa bile verdigimiz degerden almasi gerekmiyor mu?

**Comment by ismailocal** [comment]
şu şekilde kullanırsan sorun hallolur.
`.dark-theme #top-navigation #options-dropdown .dropdown-toggle svg{ fill: #d89630!important; }`
.dropdown-toggle'a bağladığın .toggles sınıfı üzerinden değer atadığında var olan base değerle replace ediyor ve bu sorun çıkıyor ama nedeni konusunda emin değilim.

**Comment by yali4** [comment]
`view-source` ile sayfa kaynağına bakarsanız gelen response'da ilgili kısım `<a class="dropdown-toggle" title="seçenekler">` şeklindedir. daha sonra `DOMContentLoaded` tetiklendiğinde bu elemente bir de `toggles` sınıfı eklenmekte. sizin seçiciniz de `toggles` sınıfı üzerinden hareket ettiği için dolaylı yoldan `DOMContentLoaded` eventinin tetiklenmesini bekliyor. @ismailocal yukarıda çözüm sunmuş. onun da söylediği gibi seçicinden `.toggles` kısmını kaldırırsan `DOMContentLoaded` beklenmeyecek.

**Comment by ismailocal** [comment]
burada beğen butonu olmadığı için sözlü ifade edecem, @yali4 açıklaman için teşekkürler. bu tür problemleri çözümleyememek ben de can sıkıntısı yapıyor. kuş gibi hafifledim, sağolasın.

**Comment by yali4** [comment]
ne demek, rica ederim.

**Comment by FatihErdem** [comment]
@yali4 aciklama icin tesekkurler. Frontend'i de yavas yavas ogrenicem bu sekilde. :)
