### ISSUE TITLE
Firefox sürümü

### ISSUE THREAD

**Issue by dcelasun** [serdarcevher/eksinormallestirici#5]
Öncelikle çok teşekkürler eklenti için. 1-2 gün içinde Firefox sürümü için pull request göndereceğim, takip etmek için açıyorum bunu.

**Comment by serdarcevher** [comment]
Ben de şimdiden teşekkür ederim emeğiniz için. Benim şu ana kadar çok fazla GitHub tecrübem olmadı o yüzden Firefox sürümü gelince dosyaların yerleştirilmesi konusunda biraz yönlendirilmeye ihtiyacım olabilir. :) Bir de haftaiçi çalışıyor olduğumdan pull request'inize geç dönüş yaparsam yanlış anlamayın lütfen.

**Comment by dcelasun** [comment]
Hiç sorun değil, ne zaman bakabilirseniz. Benim de Firefox'un yeni Addon SDK'sıyla ilk deneyimim olacak. XUL zamanından kalmayım maalesef :)
