### ISSUE TITLE
eksinumarator ve gormemisin oglu hakkında 

### ISSUE THREAD

**Issue by inalincedal** [serdarcevher/eksinormallestirici#8]
Merhaba sahtepetrucci, bir ricam olacaktı.

eksi hesabim olmadığı için https://eksisozluk.com/entry/58853045 numararlı entryde "gormemisin oglu" isimli kullanıcının hırsızlıkla itham etmeleri dogrultusunda alttaki açıklamaları okuması için iletmenizi rica edeceğim

https://eksisozluk.com/eksinumarator--4860903 basligi 21.07.2015 tarihinde acilmis. Muhtemelen aynı dönemlerde yazıldığını düşünüyorum. eksinormallestirici reposuna eklediğim kodlar 24.03.2015 tarihinde yazdıgım extensiondan alıp buraya gönderdiğim kodlardır. Sadece entry numaralarını gösteren bir extensiondır.

https://chrome.google.com/webstore/detail/ek%C5%9Fis%C3%B6zl%C3%BCk-entry-numarala/cbiidodddbbebnhdfinllmjnjnpofahk?hl=en

Extensionın ne zaman yaratıldığını gösteren ekran görüntüsü  -> [http://i.imgur.com/4ICWuUP.png](http://i.imgur.com/4ICWuUP.png)

eksinumarator kodlarını incelemedim ama ortada bir hırsızlıktan bahsediliyorsa hırsızın kim olduğu ortadadır.

tesekkurler.

**Comment by serdarcevher** [comment]
Merhaba, çok teşekkürler bu bilgi için, içim ferahladı. Aynen ilettim, ekşi sözlük'te konuyla ilgili yazdığım entry'nin de altına ekledim.

**Comment by btdogan** [comment]
Minareyi calan kilifi hazirlar misali arkadas daha hazirladigi bir exstension'in ismini cismini degistirip gondermis. Bu kadar da olmaz yahu! Edep, vallahi billahi edep!!! Ac bir kodlara bak, anlayacaksin ne demek istedigimi. Bu densizlik devam ederse mahkemeye verecegim haberiniz olsun

**Comment by inalincedal** [comment]
Kodlardaki tek benzerlik linkteki save_options/restore_options fonksiyonları ve commentler. Bunu da zaten google ın kendi dökümanlarından almışız. Alttaki linki inceleyebilirsin. (Ayrıca senin repo benim extensionı markete eklememden 4 ay sonra açılmış). Aslına bakarsan ne sen benden ne de ben senden kod aldım.

https://developer.chrome.com/extensions/options

Sonuca gelecek olursak İki satır dandik js kodu için konuyla ilgilenecek vaktim yok. Konuda ısrarcıysan dokumantasyonlarında senin kodunu kullandıkları için Google'ı mahkemeye verebilirsin :)

**Comment by kerembeyazit** [comment]
@btdogan Skynet'in kaynak kodlarını çalınmış gibi davranıyorsun. Bence gereksiz atar yapıyorsun.

**Comment by serdarcevher** [comment]
Ya arkadaş bana attığı özel mesajda da jQuery'i include etmiş olmamızın kodun çalıntı olduğuna işaret ettiğini söylüyor (detayını kaldırayım da bir de özel mesajın ifşası derdimiz olmasın).

Nasıl ciddiye alıp da cevap vereyim. :)

**Comment by yali4** [comment]
@btdogan  Üçbeş satır JavaScript kodu için bence de gereksiz atar yapıyorsun.
